name = "rise-lean"
version = "0.1.0"
defaultTargets = ["rise-lean"]

[[lean_lib]]
name = "RiseLean"

[[lean_lib]]
name = "Elevate"

[[lean_lib]]
name = "Assert"

[[lean_exe]]
name = "rise-lean"
root = "Main"
